name: Juice Shop Pipeline 

on:
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d

      - name: List containers
        run: docker ps
