name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Juice Shop image
        run: docker pull bkimminich/juice-shop

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bkimminich/juice-shop'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
